name: Build Dunder Mifflin application

run-name: Build Dunder Mifflin application

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PUBLISH_DIR: 'publish'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 9.0

      - name: Restore dependencies
        working-directory: src
        run: dotnet restore

      - name: Build
        working-directory: src
        run: dotnet build --no-restore --configuration Release

      - name: Publish
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          dotnet publish ./Your.Api.csproj \
            --configuration Release \
            --output ${{ env.PUBLISH_DIR }}
          # Zip what App Service expects (folder content)
          cd ${{ env.PUBLISH_DIR }} && zip -r ../app.zip . && cd -

      - name: Upload artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: dundermifflin-artifact
          path: app.zip
