name: Deploy Dunder Mifflin application

run-name: Deploy Dunder Mifflin application

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    environment: Dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
