name: Deploy Dunder Mifflin application

run-name: Deploy Dunder Mifflin application

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    environment: Dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Check and create resource group if it doesn't exist
        run: |
          RG_NAME="dundermifflin-rg"
          LOCATION="westeurope"

          if az group show --name $RG_NAME &>/dev/null; then
            echo "Resource group '$RG_NAME' already exists."
          else
            echo "Creating resource group '$RG_NAME' in $LOCATION..."
            az group create --name $RG_NAME --location $LOCATION
          fi

      - name: Check Bicep
        working-directory: bicep
        run: |
          az deployment group what-if `
          --resource-group dundermifflin-rg `
          --template-file "main.bicep"
