name: Deploy Dunder Mifflin application

run-name: Deploy Dunder Mifflin application

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  DeployApp:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: Dev
    timeout-minutes: 15

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: feature/deploy-app # temporary while testing
          name: dundermifflin-artifact
          workflow_conclusion: success
          path: artifact
          skip_unpack: true

      - name: Azure login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Deploy app
        uses: Azure/webapps-deploy@v3.0.6
        with:
          app-name: dundermifflin-app-azurefest # Temp name because dundermifflin-app is being held hostage in another subscription
          package: artifact/dundermifflin-artifact

