name: Deploy Dunder Mifflin application

run-name: Deploy Dunder Mifflin application

on:
  workflow_dispatch:

env:
  resourceGroupName: dundermifflin-rg

permissions:
  id-token: write
  contents: read

jobs:
  DeployApp:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: Dev
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
