name: Build and deploy Dunder Mifflin application

run-name: Build and deploy

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 9.0

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src

      - name: Build
        run: dotnet build --no-restore --configuration Release
